export const FETCH_YOUTUBE_VIDEOS = "FETCH_YOUTUBE_VIDEOS";
export const FETCH_YOUTUBE_VIDEOS_SUCCESS = "FETCH_YOUTUBE_VIDEOS_SUCCESS";
export const FETCH_YOUTUBE_VIDEOS_FAILUR = "FETCH_YOUTUBE_VIDEOS_FAILUR";
